CoNekT/conekt/forms/blast.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SelectField
from wtforms.validators import InputRequired


class BlastForm(FlaskForm):
    blast_type = SelectField('blast_type')
    fasta = TextAreaField('fasta', [InputRequired()])

    def populate_blast_types(self):
        self.blast_type.choices = [('blastp',  'blastp'), ('blastn', 'blastn')]

CoNekT/conekt/forms/export_condition.py
from flask_wtf import FlaskForm
from wtforms import SelectField

from conekt.models.species import Species


class ExportConditionForm(FlaskForm):
    species = SelectField('Species')
    methods = SelectField('Method')
    conditions = SelectField('Condition')

    def populate_form(self):
        self.species.choices = [(0, "Select species")] + [(s.id, s.name) for s in Species.query.order_by(Species.name)]
        self.methods.choices = [(0, "Select species first")]
        self.conditions.choices = [(0, "Select species first")]

CoNekT/conekt/controllers/blast.py
from flask import Blueprint, current_app, Response, redirect, url_for, request, render_template, flash
from sqlalchemy.sql.expression import func

from conekt import blast_thread
from conekt.models.sequences import Sequence
from conekt.forms.blast import BlastForm

import os
import json
import random
import string
from collections import OrderedDict
from time import sleep

blast = Blueprint('blast', __name__)


@blast.route('/', methods=['GET', 'POST'])
def blast_main():
    """
    Main blast interface

    GET request: the html with the blast form will be returned
    POST requests: the input will be validated and the blast will be started
    """
    form = BlastForm(request.form)
    form.populate_blast_types()
    
    if request.method == 'POST' and form.validate():
        blast_type = request.form.get('blast_type')
        fasta = request.form.get('fasta')

        token = ''.join([random.choice(string.ascii_letters) for _ in range(18)])
        file_in = os.path.join(current_app.config['BLAST_TMP_DIR'], token + '.in')
        file_out = os.path.join(current_app.config['BLAST_TMP_DIR'], token + '.out')

        with open(file_in, 'w') as f:
            print(fasta, file=f)

        blast_thread.add_job(blast_type, file_in, file_out)

        return redirect(url_for('blast.blast_results', token=token))

    if form.errors:
        flash(form.errors, 'danger')

    # select example from the database
    sequence = Sequence.query.filter(Sequence.type == 'protein_coding')\
        .filter(func.length(Sequence.coding_sequence) > 300).first()

    example = {
        'blast_type': 'blastp',
        'fasta': sequence.protein_sequence if sequence is not None else None
    }

    return render_template('blast.html', form=form, example=example)


@blast.route('/results/<token>')
def blast_results(token):
    """
    Renders the blast results for a given token

    :param token: code for the generated results
    :return: page containing the blast results
    """
    return render_template('blast.html', token=token)


@blast.route('/results/json/<token>')
def blast_results_json(token):
    """
    Returns a json file with the status of the blast and the results in case it is completed

    :param token: code for the generated results
    :return: json object with the blast status and results
    """
    file_results = os.path.join(current_app.config['BLAST_TMP_DIR'], token + '.out')
    file_in = os.path.join(current_app.config['BLAST_TMP_DIR'], token + '.in')
    columns = ['query', 'hit', 'percent_identity', 'alignment_length', 'num_mismatch',
               'num_gaps', 'q_start', 'q_end', 'h_start', 'h_end', 'e_value', 'bit_score']

    # Check if output exists and is writeable (which indicates the move is completed... i hope)
    if os.path.exists(file_results) and os.access(file_results, os.W_OK):
        # sleep(0.2) #might be necessary in case the os.access doesn't do the trick
        output = []

        with open(file_results) as f:
            for line in f:
                output.append(OrderedDict(zip(columns, line.split())))

        return Response(json.dumps({'status': 'done', 'data': output}), mimetype='application/json')
    else:
        if not os.path.exists(file_in):
            return Response(json.dumps({'status': 'error',
                                        'message': 'An error occurred. Error with input or results expired'}),
                            mimetype='application/json')
        else:
            return Response(json.dumps({'status': 'waiting'}), mimetype='application/json')

CoNekT/conekt/controllers/cazyme.py
from flask import Blueprint, redirect, url_for, render_template, Response, g
from sqlalchemy.orm import joinedload

from conekt import cache
from conekt.helpers.chartjs import prepare_doughnut
from conekt.models.cazyme import CAZYme
from conekt.models.sequences import Sequence

import json

cazyme = Blueprint('cazyme', __name__)


@cazyme.route('/')
def cazyme_overview():
    """
    For lack of a better alternative redirect users to the main page
    """
    return redirect(url_for('main.screen'))


@cazyme.route('/find/<cazyme_label>')
@cache.cached()
def cazyme_find(cazyme_family):
    """
    Find a cazyme term based on the family and show the details for this term

    :param cazyme_label: Label of the CAZYme term
    """
    current_cazyme = CAZYme.query.filter_by(family=cazyme_family).first_or_404()

    return redirect(url_for('cazyme.cazyme_view', cazyme_id=current_cazyme.id))


@cazyme.route('/view/<cazyme_id>')
@cache.cached()
def cazyme_view(cazyme_id):
    """
    Get a cazyme term based on the ID and show the details for this term

    :param cazyme_id: ID of the cazyme term
    """
    current_cazyme = CAZYme.query.get_or_404(cazyme_id)
    seqIDs = {}
    sequences = current_cazyme.sequences.with_entities(Sequence.id).all()

    for s in sequences:
        seqIDs[s.id] = ""

    sequence_count = len(seqIDs)

    return render_template('cazyme.html', cazyme=current_cazyme, count=sequence_count)


@cazyme.route('/sequences/<cazyme_id>/')
@cazyme.route('/sequences/<cazyme_id>/<int:page>')
@cache.cached()
def cazyme_sequences(cazyme_id, page=1):
    """
    Returns a table with sequences with the selected cazyme

    :param cazyme_id: Internal ID of the CAZYme term
    :param page: Page number
    """
    sequences = CAZYme.query.get(cazyme_id).sequences.\
        group_by(Sequence.id).paginate(page,
                                       g.page_items,
                                       False).items

    return render_template('pagination/sequences.html', sequences=sequences)


@cazyme.route('/sequences/table/<cazyme_id>')
@cache.cached()
def cazyme_sequences_table(cazyme_id):
    sequences = CAZYme.query.get(cazyme_id).sequences.\
        group_by(Sequence.id).options(joinedload('species')).order_by(Sequence.name)

    return Response(render_template('tables/sequences.csv', sequences=sequences), mimetype='text/plain')


@cazyme.route('/json/species/<cazyme_id>')
@cache.cached()
def cazyme_json_species(cazyme_id):
    """
    Generates a JSON object with the species composition that can be rendered using Chart.js pie charts or doughnut
    plots

    :param cazyme_id: ID of the cazyme term to render
    """
    # TODO: This function can be improved with the precalculated counts !

    current_cazyme = CAZYme.query.get_or_404(cazyme_id)
    sequences = current_cazyme.sequences.options(joinedload('species')).all()

    counts = {}

    for s in sequences:
        if s.species.code not in counts.keys():
            counts[s.species.code] = {}
            counts[s.species.code]["label"] = s.species.name
            counts[s.species.code]["color"] = s.species.color
            counts[s.species.code]["highlight"] = s.species.highlight
            counts[s.species.code]["value"] = 1
        else:
            counts[s.species.code]["value"] += 1

    plot = prepare_doughnut(counts)

    return Response(json.dumps(plot), mimetype='application/json')


@cazyme.route('/json/genes/<cazyme_label>')
@cache.cached()
def cazyme_genes_find(cazyme_label):
    current_cazyme = CAZYme.query.filter_by(label=cazyme_label).first()

    if current_cazyme is not None:
        return Response(json.dumps([association.sequence_id for association in current_cazyme.sequence_associations]),
                        mimetype='application/json')
    else:
        return Response(json.dumps([]), mimetype='application/json')

@cazyme.route('/ajax/cazyme/<cazyme_id>')
@cache.cached()
def cazyme_cazyme_ajax(cazyme_id):
    current_cazyme = CAZYme.query.get(cazyme_id)

    return render_template('async/cazyme_stats.html',
                           cazyme_stats={k: v for k, v in current_cazyme.cazyme_stats.items() if str(k) != str(cazyme_id)})


@cazyme.route('/ajax/family/<cazyme_id>')
@cache.cached()
def cazyme_family_ajax(cazyme_id):
    current_cazyme = CAZYme.query.get(cazyme_id)

    return render_template('async/family_stats.html', family_stats=current_cazyme.family_stats)

CoNekT/conekt/controllers/clade.py
from flask import Blueprint, redirect, url_for, render_template, g, Response

from conekt import cache
from conekt.models.clades import Clade
from conekt.models.relationships.cluster_clade import ClusterCladeEnrichment
from conekt.models.species import Species
from conekt.models.gene_families import GeneFamily
from conekt.models.interpro import Interpro

import json

clade = Blueprint('clade', __name__)


@clade.route('/')
def clade_overview():
    """
    For lack of a better alternative redirect users to the main page
    """
    return redirect(url_for('main.screen'))


@clade.route('/view/<clade_id>')
@cache.cached()
def clade_view(clade_id):
    """
    Get all information for the desired clade and return the main view

    :param clade_id: internal ID of the clade
    """
    current_clade = Clade.query.get_or_404(clade_id)

    species_codes = json.loads(current_clade.species)

    species = Species.query.filter(Species.code.in_(species_codes)).order_by(Species.name).all()

    families_count = current_clade.families.count()
    interpro_count = current_clade.interpro.count()
    cluster_count = current_clade.enriched_clusters.count()
    association_count = current_clade.sequence_sequence_clade_associations.count()

    return render_template('clade.html', clade=current_clade,
                           families_count=families_count, interpro_count=interpro_count, cluster_count=cluster_count,
                           association_count=association_count, species=species)


@clade.route('/families/<int:clade_id>/')
@clade.route('/families/<int:clade_id>/<int:page>')
@cache.cached()
def clade_families(clade_id, page=1):
    """
    Paginated list of families that emerged in this clade

    :param clade_id: internal clade ID
    :param page: page number
    :return: html-response which can be used in combination with the pagination code
    """
    current_clade = Clade.query.get_or_404(clade_id)
    families = current_clade.families.order_by(GeneFamily.name).paginate(page,
                                                                         g.page_items,
                                                                         False).items

    return render_template('pagination/families.html', families=families)


@clade.route('/families/table/<int:clade_id>')
@cache.cached()
def clade_families_table(clade_id):
    """
    Returns a table (csv) of all families that emerged in this clade

    :param clade_id: internal clade id
    :return: plain text response with csv file
    """
    families = Clade.query.get(clade_id).families.order_by(GeneFamily.name)

    return Response(render_template('tables/families.csv', families=families), mimetype='text/plain')


@clade.route('/interpro/<int:clade_id>/')
@clade.route('/interpro/<int:clade_id>/<int:page>')
@cache.cached()
def clade_interpro(clade_id, page=1):
    """
    Paginated list of InterPro domains that emerged in this clade

    :param clade_id: internal clade ID
    :param page: page number
    :return: html-response which can be used in combination with the pagination code
    """
    current_clade = Clade.query.get_or_404(clade_id)
    interpro = current_clade.interpro.order_by(Interpro.label).paginate(page,
                                                                        g.page_items,
                                                                        False).items

    return render_template('pagination/interpro.html', interpro=interpro)


@clade.route('/interpro/table/<int:clade_id>')
@cache.cached()
def clade_interpro_table(clade_id):
    """
    Returns a table (csv) of all InterPro domains that emerged in this clade

    :param clade_id: internal clade id
    :return: plain text response with csv file
    """
    interpro = Clade.query.get(clade_id).interpro.order_by(Interpro.label)

    return Response(render_template('tables/interpro.csv', interpro=interpro), mimetype='text/plain')


@clade.route('/clusters/<int:clade_id>/')
@clade.route('/clusters/<int:clade_id>/<int:page>')
@cache.cached()
def clade_clusters(clade_id, page=1):
    """
    Paginated list of clusters that are enriched for this clade

    :param clade_id: internal clade ID
    :param page: page number
    :return: html-response which can be used in combination with the pagination code
    """
    current_clade = Clade.query.get_or_404(clade_id)
    clusters = current_clade.enriched_clusters.\
        order_by(ClusterCladeEnrichment.corrected_p_value.asc()).paginate(page, g.page_items, False).items

    return render_template('pagination/clusters.html', clusters=clusters)


@clade.route('/associations/<int:clade_id>/')
@clade.route('/associations/<int:clade_id>/<int:page>')
@cache.cached()
def clade_associations(clade_id, page=1):

    current_clade = Clade.query.get_or_404(clade_id)
    associations = current_clade.sequence_sequence_clade_associations.paginate(page,
                                                                               g.page_items,
                                                                               False).items

    return render_template('pagination/clade_relations.html', relations=associations)

CoNekT/conekt/controllers/help.py
from flask import Blueprint, render_template, abort

from conekt import cache

# Dict containing all keywords and the template with the information
__TOPICS = {"gene_family": "modals/help/gene_family.html",
            "interpro_domain": "modals/help/interpro_domain.html",
            "go": "modals/help/go.html",
            "correction": "modals/help/fdr.html",
            "fdr": "modals/help/fdr.html",
            "ecc": "modals/help/ecc.html",
            "spm": "modals/help/spm.html",
            "entropy": "modals/help/entropy.html",
            "tau": "modals/help/tau.html",
            "cluster": "modals/help/cluster.html",
            "neighborhood": "modals/help/neighborhood.html",
            "hrr": "modals/help/hrr.html",
            "blast": "modals/help/blast.html",
            "pcc": "modals/help/pcc.html",
            "lowabundance": "modals/help/low_abundance.html",
            "sequence_ontology": "modals/help/sequence_ontology.html"}

__POPUPS = {"lowabundance": "tooltips/low_abundance.html"}

help = Blueprint('help', __name__)


@help.route('/<topic>')
@cache.cached()
def help_topic(topic):
    """
    Generic function to get help modals.

    :param topic: name of the topic
    :return: renders template for the topic if found, 404 if not.
    """
    if topic in __TOPICS.keys():
        return render_template(__TOPICS[topic])
    else:
        abort(404)


@help.route('/popup/<topic>')
@cache.cached()
def help_popup(topic):
    """
    Generic function to get help popups

    :param topic: name of the topic
    :return: renders template for the topic if found, 404 if not.
    """
    if topic in __POPUPS.keys():
        return render_template(__POPUPS[topic])
    else:
        abort(404)

CoNekT/conekt/controllers/main.py
from flask import Blueprint, render_template, current_app, redirect, g, flash, url_for

from conekt.models.news import News

main = Blueprint('main', __name__)


@main.route('/')
def screen():
    """
    Shows the main screen
    """

    keyword_examples = current_app.config['KEYWORD_EXAMPLES'] if'KEYWORD_EXAMPLES' in current_app.config.keys() else None

    news = News.query.order_by(News.posted.desc()).limit(5)

    return render_template('static_pages/main.html', news=news, keyword_examples=keyword_examples)


@main.route('/features')
def features():
    """
    Shows overview of features
    """
    return render_template('static_pages/features.html')


@main.route('/about')
def about():
    """
    Shows the about page
    """
    return render_template('static_pages/about.html')


@main.route('/contact')
def contact():
    """
    Shows the about contact
    """
    return render_template('static_pages/contact.html')

@main.route('/data-resources')
def data_resources():
    """
    Shows the data resources page
    """
    return render_template('static_pages/data_resources.html')


@main.route('/disclaimer')
def disclaimer():
    """
    Shows the disclaimer
    """
    return render_template('static_pages/disclaimer.html')


@main.route('/privacy')
def privacy_policy():
    """
    Shows the privacy policy
    """
    return render_template('static_pages/privacy_policy.html')


@main.route('/imprint')
def imprint():
    if g.imprint is not None:
        return redirect(g.imprint)
    else:
        flash("No Imprint URL defined", "warning")
        redirect(url_for("main.main"))

CoNekT/conekt/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/bootstrap-slider.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/jquery.qtip.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/typeahead.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/tabbed_panel.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/phyd3.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/cookieconsent.min.css') }}" />
        <script src="{{ url_for('static', filename='js/cookieconsent.min.js') }}"></script>
        <script>
        window.addEventListener("load", function(){
        window.cookieconsent.initialise({
          "palette": {
            "popup": {
              "background": "#000"
            },
            "button": {
              "background": "#f1d600"
            }
          },
          "position": "bottom-right"
        })});
        </script>
    </head>
    <body data-spy="scroll" data-target="#navbar-side" data-offset="55">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container clearfix">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand hidden-xs" href="{{ url_for('main.screen') }}"><img src="{{ url_for('static', filename='img/icon-48x48.png') }}" style="max-width:100px;margin-left:-7px;margin-top: -13px;float:left;margin-right:5px;" width="48px"/></a>
                    <a class="navbar-brand visible-xs" href="{{ url_for('main.screen') }}"><img src="{{ url_for('static', filename='img/icon-32x32.png') }}" style="max-width:100px; margin-top: -7px;" width="32px"/></a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="{{ url_for('species.species_overview') }}">Species</a></li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Expression Profiles</li>
                                <li><a href="{{ url_for('profile_comparison.profile_comparison_main') }}">Compare profiles</a></li>
                                <li><a href="{{ url_for('heatmap.heatmap_main') }}">Create heatmap</a></li>
                                <li><a href="{{url_for('expression_profile.export_expression_levels')}}">Export expression levels</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Expression Specificity</li>
                                <li><a href="{{ url_for('specificity_comparison.specificity_comparison_main') }}">Compare specificities</a></li>
                                <li><a href="{{ url_for('search.search_specific_profiles') }}">Find specific profiles</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Co-expression Networks</li>
                                <li><a href="{{ url_for('custom_network.custom_network_main') }}">Create custom network</a></li>
                                <li><a href="{{ url_for('search.search_enriched_clusters') }}">Find enriched clusters</a></li>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Search <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('search.advanced') }}">Search <span class="text-muted">(advanced)</span></a></li>
                                {% if g.blast_enabled %}
                                    <li class="divider"></li>
                                    <li><a href="{{ url_for('blast.blast_main') }}">BLAST</a></li>
                                {% endif %}

                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form class="navbar-form"  role="search" method="post" id="search-form" name="search-form" action="{{ url_for('search.simple') }}">
                                {{ g.search_form.csrf_token }}
                                <div class="form-group input-group">
                                    {{ g.search_form.terms(class_="form-control", placeholder="Search") }}
                                    <div class="input-group-btn"><button type="submit" class="btn btn-primary" value="Search" data-toggle="modal" data-target="#loaderModal"><i class="fa fa-search"></i></button></div>
                                </div>

                            </form>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Help <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                    {% if g.tutorial %}
                                    <li><a href="{{ g.tutorial }}">Tutorial <span class="text-muted"></span></a></li>
                                    {% endif %}
                                    <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
                                </li>
                            </ul>
                        </li>
                        {% if g.msg %}
                        <li class="dropdown">
                            <a href="#" data-toggle="popover" data-html="true" data-placement="bottom" title="{{ g.msg_title }}" data-content="{{ g.msg }}"><i class="fa fa-envelope"><span class="badge badge-notify">!</span></i></a>
                        </li>
                        {% endif%}
                    </ul>
                </div>
            </div>
        </div>



        <!-- Code to get flash function working -->
        <div class="container">
            {% for category, message in get_flashed_messages(with_categories=true) %}
            <br />
            <div class="alert alert-{{category}} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
        </div>

        <div class="container">
            {% block container %}{% endblock %}
        </div>

        <footer class="footer" id="footer">
          <div class="container">
              <div class="row">
                  <div class="col-xs-2"><strong class="text-muted"><a href="{{ url_for('main.features') }}" class="text-muted">CoNekT</a></strong></div>
                  <div class="col-xs-2"><a href="{{ url_for('main.about') }}" class="text-muted">About</a></div>
                  <div class="col-xs-2"><a href="{{ url_for('main.contact') }}" class="text-muted">Contact</a></div>
                  <div class="col-xs-2"><a href="{{ url_for('main.disclaimer') }}" class="text-muted">Disclaimer</a></div>
                  <div class="col-xs-2"><a href="{{ url_for('main.privacy_policy') }}" class="text-muted">Privacy policy</a></div>
                  <div class="col-xs-2"><a href="{{ url_for('main.data_resources') }}" class="text-muted">Data resources</a></div>
                  {% if g.imprint %}
                    <div class="col-xs-2"><a href="{{ url_for('main.imprint') }}" class="text-muted">Imprint</a></div>
                  {% endif %}
              </div>
          </div>
        </footer>
        <div class="modal" id="helpModal" tabindex="-1" role="dialog" aria-labelledby="helpModalLabel">
            <div class="modal-dialog" role="document" style="width:1000px;height:800px;">
            <div class="modal-content">

            </div>

        </div>
        </div>
        <div class="modal" id="loaderModal" tabindex="-1" role="dialog" aria-labelledby="loaderModalLabel">
          <div class="modal-dialog" role="document" style="width:1000px;height:800px;">
            <div class="modal-content">
                <div class="modal-body">
                <div id="leafy_loader"></div>
                <p class="text-center text-muted" id="leafy_loader_text">Loading ... please wait ... </p>
                <p class="text-center" id="leafy_loader_close_btn" style="display:none"><button type="button" class="btn btn-primary" data-dismiss="modal">Close</button></p>
                </div>
            </div>
          </div>
        </div>

        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/stupidtable.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/TweenMax.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.qtip.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/planet_loader.js') }}"></script>
        <!-- code to reload modal on each click -->
        <script>
        function init_qtip() {
                   $('.qtip_tooltip').each(function() {
                     $(this).qtip({
                        content: {
                            text: function(event, api) {
                                $.ajax({
                                    url: api.elements.target.attr('qtip_href')
                                })
                                .then(function(content) {
                                    // Set the tooltip content upon successful retrieval
                                    api.set('content.text', content);
                                }, function(xhr, status, error) {
                                    // Upon failure... set the tooltip content to error
                                    api.set('content.text', status + ': ' + error);
                                });

                                return 'Loading...'; // Set some initial text
                            }
                        },
                        show: {
                            effect: function() {
                                $(this).fadeTo(500, 1);
                            }
                        },
                        hide: {
                            effect: function() {
                                $(this).fadeTo(500, 0);
                            }
                        },
                        position: {
                            viewport: $(window)
                        },
                        style: 'qtip-bootstrap'
                     });
                 });
        }

          $(function () {
              init_qtip();

              $("#leafy_loader").html(get_loader_svg('loader_leafy'));
              init_planet_loader('loader_leafy');

              $('[data-toggle="popover"]').popover({container: 'body'});

              $('a[data-target=#helpModal], abbr[data-target=#helpModal]').click(function(ev) {
                ev.preventDefault();
                var target = $(this).attr("href");

                // load the url and show modal on success
                $("#helpModal .modal-content").load(target, function() {
                     $("#helpModal").modal("show");
                });
              });
            });
        </script>
        <script src="{{ url_for('static', filename='js/planet_pagination.js') }}"></script>
        <script src="{{ url_for('static', filename='js/planet_ajax_table.js') }}"></script>
        <script type="text/javascript">
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
        </script>
{% block extrajs %}{% endblock %}
</body>
</html>