CoNekT/conekt/models/literature.py
from conekt import db

SQL_COLLATION = None


class LiteratureItem(db.Model):
    __tablename__ = 'literature'
    id = db.Column(db.Integer, primary_key=True)
    qtd_author = db.Column(db.Integer, nullable=False)
    author_names = db.Column(db.String(100, collation=SQL_COLLATION), nullable=False)
    title = db.Column(db.String(250, collation=SQL_COLLATION), nullable=False)
    public_year = db.Column(db.Integer, nullable=False)
    doi = db.Column(db.String(100, collation=SQL_COLLATION), nullable=False,
                    unique=True)

    def __init__(self, qtd_author, author_names, title, public_year, doi):
        self.qtd_author = qtd_author
        self.author_names = author_names
        self.title = title
        self.public_year = public_year
        self.doi = doi

    def __repr__(self):
        return str(self.id) + ". " + (f'{self.author_names} ({self.public_year})')

CoNekT/conekt/controllers/ecc.py
from flask import Blueprint, redirect, url_for, render_template
from sqlalchemy import and_

from conekt.models.sequences import Sequence
from conekt.models.relationships.sequence_sequence_ecc import SequenceSequenceECCAssociation

from conekt.helpers.cytoscape import CytoscapeHelper

import json

ecc = Blueprint('ecc', __name__)


@ecc.route('/')
def ecc_overview():
    """
    For lack of a better alternative redirect users to the main page
    """
    return redirect(url_for('main.screen'))


@ecc.route('/graph/<int:sequence>/<int:network>/<int:family>')
def ecc_graph(sequence, network, family):
    """
    Returns a page rendering the ECC graph for a specific sequence

    :param sequence: Internal ID of a sequence
    :param network: Internal ID of the network method
    :param family: Internal ID of the family method
    :return: Response with html page that shows the ECC network
    """
    sequence = Sequence.query.get_or_404(sequence)
    return render_template("expression_graph.html",
                           sequence=sequence,
                           network_method_id=network,
                           family_method_id=family)


@ecc.route('/graph_multi/')
def ecc_graph_multi():
    """
    Returns a page rendering the ECC graph for a specific pair of sequences

    :param ecc_id: internal ID of the sequence to sequence ECC relationship
    :return: Response with html page that shows the pairwise ECC network
    """

    return render_template("expression_graph.html",
                           ecc_multi=True)


@ecc.route('/graph_pair/<int:ecc_id>')
def ecc_graph_pair(ecc_id):
    """
    Returns a page rendering the ECC graph for a specific pair of sequences

    :param ecc_id: internal ID of the sequence to sequence ECC relationship
    :return: Response with html page that shows the pairwise ECC network
    """
    ecc_pair = SequenceSequenceECCAssociation.query.get_or_404(ecc_id)

    return render_template("expression_graph.html",
                           ecc_pair=ecc_pair)


@ecc.route('/json/<int:sequence>/<int:network>/<int:family>')
def ecc_graph_json(sequence, network, family):
    """
    Returns a JSON object compatible with cytoscape.js that contains the ECC graph for a specific sequence

    :param sequence: Internal ID of a sequence
    :param network: Internal ID of the network method
    :param family: Internal ID of the family method
    :return: JSON object compatible with cytoscape.js
    """

    network = SequenceSequenceECCAssociation.get_ecc_network(sequence, network, family)

    network_cytoscape = CytoscapeHelper.parse_network(network)
    network_cytoscape = CytoscapeHelper.add_descriptions_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.add_family_data_nodes(network_cytoscape, family)
    network_cytoscape = CytoscapeHelper.add_lc_data_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.add_species_data_nodes(network_cytoscape)

    return json.dumps(network_cytoscape)


@ecc.route('/pair_json/<int:ecc_id>')
def ecc_graph_pair_json(ecc_id):
    """
    Returns a JSON object compatible with cytoscape.js that contains the ECC graph for a specific pair of sequences

    :param ecc_id: internal ID of the sequence to sequence ECC relationship
    :return: JSON object compatible with cytoscape.js
    """
    network, family = SequenceSequenceECCAssociation.get_ecc_pair_network(ecc_id)

    network_cytoscape = CytoscapeHelper.parse_network(network)
    network_cytoscape = CytoscapeHelper.add_descriptions_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.add_family_data_nodes(network_cytoscape, family)
    network_cytoscape = CytoscapeHelper.add_lc_data_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.add_species_data_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.connect_homologs(network_cytoscape)
    network_cytoscape = CytoscapeHelper.tag_ecc_singles(network_cytoscape)

    return json.dumps(network_cytoscape)


@ecc.route('/multi_json/')
def ecc_graph_multi_json():
    """
    Returns a JSON object compatible with cytoscape.js that contains the ECC graph for a specific pair of sequences

    :param ecc_id: internal ID of the sequence to sequence ECC relationship
    :return: JSON object compatible with cytoscape.js
    """
    network, family = SequenceSequenceECCAssociation.get_ecc_multi_network(1, [162930, 56261, 203621, 94050])

    network_cytoscape = CytoscapeHelper.parse_network(network)
    network_cytoscape = CytoscapeHelper.add_descriptions_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.add_family_data_nodes(network_cytoscape, family)
    network_cytoscape = CytoscapeHelper.add_lc_data_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.add_species_data_nodes(network_cytoscape)
    network_cytoscape = CytoscapeHelper.connect_homologs(network_cytoscape)
    network_cytoscape = CytoscapeHelper.tag_ecc_singles(network_cytoscape)

    return json.dumps(network_cytoscape)

CoNekT/conekt/controllers/interpro.py
from flask import Blueprint, redirect, url_for, render_template, Response, g
from sqlalchemy.orm import joinedload, noload

from conekt import cache
from conekt.helpers.chartjs import prepare_doughnut
from conekt.models.interpro import Interpro
from conekt.models.sequences import Sequence

import json

interpro = Blueprint('interpro', __name__)


@interpro.route('/')
def interpro_overview():
    """
    For lack of a better alternative redirect users to the main page
    """
    return redirect(url_for('main.screen'))


@interpro.route('/find/<interpro_domain>')
@cache.cached()
def interpro_find(interpro_domain):
    """
    Find an interpro domain based on the label and show the details for this domain

    :param interpro_domain: Name of the interpro domain
    """
    current_interpro = Interpro.query.filter_by(label=interpro_domain).first_or_404()

    return redirect(url_for('interpro.interpro_view', interpro_id=current_interpro.id))


@interpro.route('/view/<interpro_id>')
@cache.cached()
def interpro_view(interpro_id):
    """
    Get an interpro domain based on the ID and show the details for this domain

    :param interpro_id: ID of the interpro domain
    """
    current_interpro = Interpro.query.get_or_404(interpro_id)
    seqIDs = {}
    sequences = current_interpro.sequences.with_entities(Sequence.id).all()

    for s in sequences:
        seqIDs[s.id] = ""

    sequence_count = len(seqIDs)

    return render_template('interpro.html', interpro=current_interpro, count=sequence_count)


@interpro.route('/sequences/<interpro_id>/')
@interpro.route('/sequences/<interpro_id>/<int:page>')
@cache.cached()
def interpro_sequences(interpro_id, page=1):
    """
    Returns a table with sequences with the selected interpro domain

    :param interpro_id: Internal ID of the interpro domain
    :param page: Page number
    """
    sequences = Interpro.query.get(interpro_id).sequences.group_by(Sequence.id)\
        .options(joinedload('species'))\
        .paginate(page, g.page_items, False).items

    return render_template('pagination/sequences.html', sequences=sequences)


@interpro.route('/sequences/table/<interpro_id>')
@cache.cached()
def interpro_sequences_table(interpro_id):
    """
    Returns a csv table with all sequences with the selected interpro domain

    :param interpro_id: Internal ID of the interpro domain
    """
    sequences = Interpro.query.get(interpro_id).sequences.group_by(Sequence.id)\
        .options(joinedload('species'))\
        .order_by(Sequence.name)

    return Response(render_template('tables/sequences.csv', sequences=sequences), mimetype='text/plain')


@interpro.route('/json/species/<interpro_id>')
@cache.cached()
def interpro_json_species(interpro_id):
    """
    Generates a JSON object with the species composition that can be rendered using Chart.js pie charts or doughnut
    plots

    :param interpro_id: ID of the interpro domain to render
    """
    current_interpro = Interpro.query.get_or_404(interpro_id)
    sequences = current_interpro.sequences.options(noload('xrefs')).all()

    counts = {}

    for s in sequences:
        if s.species.code not in counts.keys():
            counts[s.species.code] = {}
            counts[s.species.code]["label"] = s.species.name
            counts[s.species.code]["color"] = s.species.color
            counts[s.species.code]["highlight"] = s.species.highlight
            counts[s.species.code]["value"] = 1
        else:
            counts[s.species.code]["value"] += 1

    plot = prepare_doughnut(counts)

    return Response(json.dumps(plot), mimetype='application/json')


@interpro.route('/ajax/interpro/<interpro_id>')
@cache.cached()
def interpro_interpro_ajax(interpro_id):
    current_interpro = Interpro.query.get(interpro_id)

    return render_template('async/interpro_stats.html',
                           interpro_stats={k: v for k, v in current_interpro.interpro_stats.items() if str(k) != str(interpro_id)})


@interpro.route('/ajax/go/<interpro_id>')
@cache.cached()
def interpro_go_ajax(interpro_id):
    current_interpro = Interpro.query.get(interpro_id)

    return render_template('async/go_stats.html', go_stats=current_interpro.go_stats)


@interpro.route('/ajax/family/<interpro_id>')
@cache.cached()
def interpro_family_ajax(interpro_id):
    current_interpro = Interpro.query.get(interpro_id)

    return render_template('async/family_stats.html', family_stats=current_interpro.family_stats)


@interpro.route('/tooltip/<interpro_id>')
@cache.cached()
def interpro_tooltip(interpro_id):
    """
    Get an interpro domain based and render in tooltip template

    :param interpro_id: ID of the interpro domain
    """
    current_interpro = Interpro.query.get_or_404(interpro_id)

    return render_template('tooltips/interpro.html', interpro=current_interpro)

CoNekT/conekt/controllers/literature.py
from flask import Blueprint, redirect, url_for, render_template

from conekt import cache

literature = Blueprint('literature', __name__)

@literature.route('/')
def literature_overview():
    """
    For lack of a better alternative redirect users to the main page
    """
    return redirect(url_for('main.screen'))

CoNekT/conekt/controllers/sequence.py
from flask import Blueprint, redirect, url_for, render_template, make_response

from conekt import cache
from conekt.models.sequences import Sequence
from sqlalchemy.orm import undefer, noload

sequence = Blueprint('sequence', __name__)


@sequence.route('/')
def sequence_overview():
	"""
	For lack of a better alternative redirect users to the main page
	"""
	return redirect(url_for('main.screen'))


@sequence.route('/find/<sequence_name>')
@cache.cached()
def sequence_find(sequence_name):
	"""
	Find a sequence based on the name and show the details for this sequence (useful for incoming links from other
	platforms)

	:param sequence_name: Name of the sequence
	"""
	current_sequence = Sequence.query.filter_by(name=sequence_name).first_or_404()

	return redirect(url_for('sequence.sequence_view', sequence_id=current_sequence.id))


@sequence.route('/view/<sequence_id>')
@cache.cached()
def sequence_view(sequence_id):
	"""
	Get a sequence based on the ID and show the details for this sequence

	:param sequence_id: ID of the sequence
	"""
	from conekt.models.relationships.sequence_go import SequenceGOAssociation
	from conekt.models.relationships.sequence_cazyme import SequenceCAZYmeAssociation
	from conekt.models.relationships.sequence_tr import SequenceTRAssociation
	from conekt.models.relationships.sequence_tr_domain import SequenceTRDomainAssociation
	from conekt.models.relationships.sequence_te_class import SequenceTEClassAssociation

	current_sequence = Sequence.query.get_or_404(sequence_id)

	go_associations = current_sequence.go_associations.group_by(SequenceGOAssociation.go_id,
																SequenceGOAssociation.evidence,
																SequenceGOAssociation.source).all()
	
	cazyme_associations = current_sequence.cazyme_associations.group_by(SequenceCAZYmeAssociation.cazyme_id).all()
	tr_associations = current_sequence.tr_associations.group_by(SequenceTRAssociation.tr_id).all()
	tr_domain_associations = current_sequence.tr_domain_associations.all()
	sequence_te_class = current_sequence.te_class_associations.group_by(SequenceTEClassAssociation.te_class_id).all()

	# to avoid running long count queries, fetch relations here and pass to template
	#expression_profiles=current_sequence.expression_profiles.all()
	return render_template('sequence.html',
						   sequence=current_sequence,
						   go_associations=go_associations,
						   interpro_associations=current_sequence.interpro_associations.all(),
						   cazyme_associations=cazyme_associations,
						   tr_associations=tr_associations,
						   tr_domain_associations=tr_domain_associations,
						   sequence_te_class=sequence_te_class,
						   families=current_sequence.families.all(),
						   expression_profiles=current_sequence.expression_profiles.all(),
						   network_nodes=current_sequence.network_nodes.all(),
						   coexpression_clusters=current_sequence.coexpression_clusters.all(),
						   ecc_query_associations=current_sequence.ecc_query_associations.all()
						   )


@sequence.route('/tooltip/<sequence_id>')
@cache.cached()
def sequence_tooltip(sequence_id):
	"""
	Get a sequence based on the ID and show the details for this sequence

	:param sequence_id: ID of the sequence
	"""
	current_sequence = Sequence.query.get_or_404(sequence_id)

	return render_template('tooltips/sequence.html', sequence=current_sequence)


@sequence.route('/modal/coding/<sequence_id>/<rna>')
def sequence_modal_coding(sequence_id, rna):
	"""
	Returns the coding sequence in a modal

	:param sequence_id: ID of the sequence
	:return: Response with the fasta file
	"""
	current_sequence = Sequence.query\
		.options(undefer('coding_sequence'))\
		.options(noload('xrefs'))\
		.get_or_404(sequence_id)
	
	name = current_sequence.name

	if rna == 'true':
		current_sequence = Sequence.query\
			.filter_by(name=name, type='RNA')\
			.options(undefer('coding_sequence'))\
			.options(noload('xrefs'))\
			.first()

	return render_template('modals/sequence.html', sequence=current_sequence, coding=True)


@sequence.route('/modal/protein/<sequence_id>')
def sequence_modal_protein(sequence_id):
	"""
	Returns the protein sequence in a modal

	:param sequence_id: ID of the sequence
	:return: Response with the fasta file
	"""
	current_sequence = Sequence.query\
		.options(undefer('coding_sequence'))\
		.options(noload('xrefs'))\
		.get_or_404(sequence_id)

	return render_template('modals/sequence.html', sequence=current_sequence, coding=False)


@sequence.route('/fasta/coding/<sequence_id>/<rna>')
def sequence_fasta_coding(sequence_id, rna):
	"""
	Returns the coding sequence as a downloadable fasta file

	:param sequence_id: ID of the sequence
	:return: Response with the fasta file
	"""

	current_sequence = Sequence.query\
		.options(undefer('coding_sequence'))\
		.options(noload('xrefs'))\
		.get_or_404(sequence_id)

	name = current_sequence.name

	if rna == 'true':
		current_sequence = Sequence.query\
			.filter_by(name=name, type='RNA')\
			.options(undefer('coding_sequence'))\
			.options(noload('xrefs'))\
			.first()

	fasta = ">" + current_sequence.name + "\n" + current_sequence.coding_sequence + "\n"
	response = make_response(fasta)
	response.headers["Content-Disposition"] = "attachment; filename=" + current_sequence.name + ".cds.fasta"
	response.headers['Content-type'] = 'text/plain'

	return response


@sequence.route('/fasta/protein/<sequence_id>')
def sequence_fasta_protein(sequence_id):
	"""
	Returns the protein sequence as a downloadable fasta file

	:param sequence_id: ID of the sequence
	:return: Response with the fasta file
	"""
	current_sequence = Sequence.query\
		.options(undefer('coding_sequence'))\
		.options(noload('xrefs'))\
		.get_or_404(sequence_id)

	fasta = ">" + current_sequence.name + "\n" + current_sequence.protein_sequence + "\n"
	response = make_response(fasta)
	response.headers["Content-Disposition"] = "attachment; filename=" + current_sequence.name + ".protein.fasta"
	response.headers['Content-type'] = 'text/plain'

	return response

CoNekT/conekt/templates/pagination/clade_relations.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for r in relations %}
                <tr>
                    <td><a href="{{ url_for('sequence.sequence_view', sequence_id=r.sequence_one_id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=r.sequence_one_id) }}">{{ r.sequence_one.name }}</a></td>
                    <td><a href="{{ url_for('sequence.sequence_view', sequence_id=r.sequence_two_id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=r.sequence_two_id) }}">{{ r.sequence_two.name }}</a></td>
                    <td><a href="{{ url_for('clade.clade_view', clade_id=r.clade_id) }}">{{ r.clade.name }}</a></td>
                    <td>{{ r.readable_type }}</td>
                    <td>{{ r.readable_score }}</td>
                    <td><a href="{{ url_for('tree.tree_view', tree_id=r.tree_id) }}">{{ r.tree.label }}</a></td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5"><em>No sequences sequence clade associations found</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/cluster_probes.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for sequence_association in sequence_associations %}
                <tr>
                    {% if sequence_association.sequence %}
                    <td><a href="{{ url_for('sequence.sequence_view', sequence_id=sequence_association.sequence.id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=sequence_association.sequence.id) }}">{{ sequence_association.sequence.name }}</a></td>
                    <td>{% if sequence_association.sequence.aliases %}{{ sequence_association.sequence.aliases }}{% else %}<span class="text-muted">No alias</span>{% endif %}</td>
                    {% else %}
                    <td><em class="text-muted">No sequence associated with this probe</em></td>
                    <td><span class="text-muted">No alias</span></td>
                    {% endif %}
                    <td>{% if sequence_association.sequence.description %}{{ sequence_association.sequence.description|truncate(60) }}{% else %}<em class="text-muted">No description available</em>{% endif %}</td>
                    <td><a href="{{ url_for('expression_profile.expression_profile_find', probe=sequence_association.probe, species_id=species_id) }}">View profile</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/clusters.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for cluster in clusters %}
                <tr>
                    <td><em><a href="{{ url_for('species.species_view', species_id=cluster.cluster.method.network_method.species_id) }}">{{ cluster.cluster.method.network_method.species.name }}</a></em></td>
                    <td><a href="{{ url_for('expression_cluster.expression_cluster_view', cluster_id=cluster.cluster_id) }}">{{ cluster.cluster.name }}</a></td>
                    <td>{{ cluster.cluster.method.method }}</td>
                    <td>{{ cluster.cluster.method.network_method.description }}</td>
                    <td>{{ cluster.gene_family_method.method }}</td>
                    <td>p-value (corrected) : {{ cluster.p_value|round(2) }} <span class="text-muted">({{ cluster.corrected_p_value|round(2) }})</span></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/ecc_relations.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <thead>
            <tr>
                <td>Query</td>
                <td>Target</td>
                <td>ECC Score</td>
                <!--<td>p-Value</td>
                <td>p-Value (corrected)</td>-->
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            {% for relation in relations %}
                <tr>
                    <td><a href="{{ url_for('sequence.sequence_view', sequence_id=relation.query_id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=relation.query_id) }}">{{ relation.query_sequence.name }}</a></td>
                    <td><a href="{{ url_for('sequence.sequence_view', sequence_id=relation.target_id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=relation.target_id) }}">{{ relation.target_sequence.name }}</a></td>
                    <td>{{ relation.ecc|round(2) }}</td>
                    <!--<td>{% if relation.p_value %}{{ relation.p_value|round(3) }}{% else %}<em class="text-muted">None</em>{% endif %}</td>
                    <td>{% if relation.corrected_p_value %}{{ relation.corrected_p_value|round(3) }}{% else %}<em class="text-muted">None</em>{% endif %}</td>-->
                    <td><a href="{{ url_for('ecc.ecc_graph_pair', ecc_id=relation.id) }}" data-toggle="tooltip"  data-placement="top" title="View ECC pair as graph"><i class="fa fa-eye"></i></a>
                        <a href="{{ url_for('ecc.ecc_graph', sequence=relation.query_id, network=relation.query_network_method_id, family=relation.gene_family_method_id) }}" data-toggle="tooltip"  data-placement="top" title="View ECC as graph"><i class="fa fa-share-alt"></i></a></td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6"><em>No ECC relations found between genes from this family</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/families.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for family in families %}
                <tr>
                    <td><a href="{{ url_for('family.family_view', family_id=family.id) }}">{{ family.name }}</a></td>
                    <td>{{ family.method.method }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/interpro.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for i in interpro %}
                <tr>
                    <td><a href="{{ url_for('interpro.interpro_view', interpro_id=i.id) }}">{{ i.label }}</a></td>
                    <td>{{ i.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/literatures.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for literature in literatures %}
                <tr>
                    <td>{{ literature.author_names }}</td>
                    <td>{{ literature.public_year }}</td>
                    <td>{{ literature.title }}</td>
                    <td><a href = "http://doi.org/{{ literature.doi }}">Link to Article</a></td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5"><em>No papers associated with this term</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/sequences.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for sequence in sequences %}
                {% if sequence.type == 'protein_coding' %}
                    <tr>
                        <td><a href="{{ url_for('sequence.sequence_view', sequence_id=sequence.id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=sequence.id) }}">{{ sequence.name }}</a></td>
                        <td>{% if sequence.aliases %}{{ sequence.aliases|truncate(20) }}{% else %}<span class="text-muted">No alias</span>{% endif %}</td>
                        <td><a href="{{ url_for('species.species_view', species_id=sequence.species_id) }}"><em>{{ sequence.species.name }}</em></a></td>
                        <td>{% if sequence.description %}{{ sequence.description|truncate(60) }}{% else %}<span class="text-muted">No description available</span>{% endif %}</td>
                        {# <td>{{ sequence.readable_type }}</td> #}
                    </tr>
                {% endif %} 
            {% else %}
                <tr>
                    <td colspan="5"><em>No sequences associated with this term</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

CoNekT/conekt/templates/pagination/transposable_elements.html
<div class="table-responsive">
    <table class="table table-striped table-separated">
        <tbody>
            {% for sequence in sequences %}
				<tr>
					<td><a href="{{ url_for('sequence.sequence_view', sequence_id=sequence.id) }}" class="qtip_tooltip qtip_dynamic_tooltip" qtip_href="{{ url_for('sequence.sequence_tooltip', sequence_id=sequence.id) }}">{{ sequence.name }}</a></td>
					<td>{% if sequence.te_classes.first() %}<a href="{{ url_for('te_class.te_class_view', te_class_id=sequence.te_classes.first().id) }}">{{ sequence.te_classes.first().name }}</a>{% else %}<span class="text-muted">No class information available</span>{% endif %}</td>
					<td>{% if sequence.te_classes.first() and sequence.te_classes.first().sequence_ontology %}<a href="{{ url_for('sequence_ontology.sequence_ontology_view', so_id=sequence.te_classes.first().sequence_ontology.id) }}">{{ sequence.te_classes.first().sequence_ontology.so_id}}</a>{% else %}<span class="text-muted">No sequence ontology available</span>{% endif %}</td>
					<td>{% if sequence.tedistills.first() %}<a href="{{ url_for('tedistill.tedistill_view', tedistill_id=sequence.tedistills.first().id) }}">{{ sequence.tedistills.first().name }}</a>{% else %}<span class="text-muted">No consense sequence available</span>{% endif %}</td>
					<td><a href="{{ url_for('species.species_view', species_id=sequence.species_id) }}"><em>{{ sequence.species.name }}</em></a></td>
					<td>{% if sequence.description %}{{ sequence.description|truncate(60) }}{% else %}<span class="text-muted">No description available</span>{% endif %}</td>
					{# <td>{{ sequence.readable_type }}</td> #}
				</tr>
            {% else %}
                <tr>
                    <td colspan="6"><em>No transposable elements associated with this term</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>