CoNekT/conekt/controllers/main.py
from flask import Blueprint, render_template, current_app, redirect, g, flash, url_for

from conekt.models.news import News

main = Blueprint('main', __name__)


@main.route('/')
def screen():
    """
    Shows the main screen
    """

    keyword_examples = current_app.config['KEYWORD_EXAMPLES'] if'KEYWORD_EXAMPLES' in current_app.config.keys() else None

    news = News.query.order_by(News.posted.desc()).limit(5)

    return render_template('static_pages/main.html', news=news, keyword_examples=keyword_examples)


@main.route('/features')
def features():
    """
    Shows overview of features
    """
    return render_template('static_pages/features.html')


@main.route('/about')
def about():
    """
    Shows the about page
    """
    return render_template('static_pages/about.html')


@main.route('/contact')
def contact():
    """
    Shows the about contact
    """
    return render_template('static_pages/contact.html')

@main.route('/data-resources')
def data_resources():
    """
    Shows the data resources page
    """
    return render_template('static_pages/data_resources.html')


@main.route('/disclaimer')
def disclaimer():
    """
    Shows the disclaimer
    """
    return render_template('static_pages/disclaimer.html')


@main.route('/privacy')
def privacy_policy():
    """
    Shows the privacy policy
    """
    return render_template('static_pages/privacy_policy.html')


@main.route('/imprint')
def imprint():
    if g.imprint is not None:
        return redirect(g.imprint)
    else:
        flash("No Imprint URL defined", "warning")
        redirect(url_for("main.main"))

CoNekT/conekt/templates/static_pages/about.html
{% extends 'base.html' %}

{% block title %}
    CoNekT - About
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li><a href="{{ url_for('main.screen') }}">Home</a></li>
        <li class="active"><strong>About</strong></li>
    </ol>
    <h1>About CoNekT Grasses</h1>
    <br />
    <p>CoNekT Grasses was developed by the Laboratory of Computational, Evolutionary and Systems Biology at the Center for Nuclear Energy in Agriculture, University of São Paulo. CoNekT Grasses is also a product of the <a href="https://www.rcgi.poli.usp.br/pt-br/">Research Centre for Greenhouse Gas Innovation</a> and the  <a href="https://bv.fapesp.br/pt/auxilios/97251/inct-2014-instituto-nacional-de-ciencia-e-tecnologia-do-bioetanol/">National Institute for Science and Technology of Bioethanol.</p></a>
    <br />


     

    <h1 class="banner-green">Funding Agencies</h1>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.gov.br/capes/pt-br" target="_blank"><img alt="capes picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;"  src="{{ url_for('static', filename='img/funding/capes_logo_250x250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.gov.br/cnpq/pt-br" target="_blank"><img alt="cnpq picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/funding/cnpq_250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://fapesp.br/" target="_blank"><img alt="fapesp picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/funding/fapesp_250.png') }}"></a>
        </div>
                             
    </div>
    <h1 class="banner-green">Institutional Support</h1>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.usp.br" target="_blank"><img alt="usp picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;"  src="{{ url_for('static', filename='img/funding/usp_logo_250x250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.cena.usp.br" target="_blank"><img alt="cena picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/funding/logo_cena_250x250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://labbces.netlify.app/" target="_blank"><img alt="bces picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/funding/bces_logo_250x250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.rcgi.poli.usp.br/" target="_blank"><img alt="rcgi picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/funding/logo_rcgi_200x200.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://inctbioetanol.ib.usp.br/" target="_blank"><img alt="inct picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/funding/logo_inct_200x200.png') }}"></a>
        </div>                        
    </div>
    
    
    <h1 class="banner-green">Computer Resources</h1>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.cenapad.unicamp.br/" target="_blank"><img alt="cenapad picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px" src="{{ url_for('static', filename='img/funding/cenapad_250.png') }}"></a>
        </div>
    </div>
    
</div>

{% endblock %}

CoNekT/conekt/templates/static_pages/contact.html
{% extends 'base.html' %}

{% block title %}
    CoNekT Grasses - Contact
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li><a href="{{ url_for('main.screen') }}">Home</a></li>
        <li class="active"><strong>Contact</strong></li>
    </ol>
    <h1>Contact Us<br /></h1>

    <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="diego picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/diego_riano_red_200.png') }}"></div>
        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Professor Dr. rer. nat. Diego M. Riaño-Pachón</h3>
            <p><strong>Group Leader</strong></p>
            <br />
            <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/diego-mauricio-riano-pachon/">LabBCES/diego-mauricio-riano-pachon</a></p>
            <p><i class="fa fa-envelope text-muted"></i> <a href="mailto:diego.riano@cena.usp.br">diego.riano@cena.usp.br</a></p>
        </div>
    </div>
    <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="renato picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/renato_santos_red_200.png') }}"></div>
        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Dr. Renato A. Corrêa dos Santos</h3>
            <p><strong>Main Developer</strong></p>
            <br />
            <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/renato-augusto-correa-dos-santos/">LabBCES/renato-augusto-correa-dos-santos</a></p>
            <p><i class="fa fa-envelope text-muted"></i> <a href="mailto:renatoacsantos@gmail.com">renatoacsantos@gmail.com</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="guilherme picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/guilherme_furlan_red_200.png') }}"></div>
            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Guilherme Furlan</h3>
                <p><strong>Dev Web</strong></p>
                <br />
                <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/guilherme-furlan/">LabBCES/guilherme-furlan</a></p>
                <p><i class="fa fa-envelope text-muted"></i> <a href="mailto:gfurlan@cena.usp.br">gfurlan@cena.usp.br</a></p>
            </div>
        </div>
        <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="jorge picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/jorge_munoz_red_200.png') }}"></div>
            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Jorge Mario Muñoz Perez</h3>
                <p><strong>PhD Student</strong></p>
                <br />
                <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/jorge-mario-munoz-perez/">LabBCES/jorge-mario-munoz-perez</a></p>
                <p><i class="fa fa-envelope text-muted"></i> <a href="mailto:jmmunozp@usp.br">jmmunozp@usp.br</a></p>
            </div>
        </div>
        <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="felipe picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/felipe_peres_red_200.png') }}"></div>
            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Felipe Vaz Peres</h3>
                <p><strong>Master Student</strong></p>
                <br />
                <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/felipe-vaz-peres/">LabBCES/felipe-vaz-peres</a></p>
                <p><i class="fa fa-envelope text-muted"></i> <a href="mailto:felipe.vzps@gmail.com">felipe.vzps@gmail.com</a></p>
            </div>
       
        </div>

    <br />
    <h1>Past Members<br /></h1>

    <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="bianca picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/bianca_pastos_red_200.png') }}"></div>
        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Bianca S. Pastos</h3>
            <p><strong>Undergraduate Student</strong></p>
            <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/bianca-pastos/">LabBCES/bianca-pastos</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="bianca picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/davidtferraz.png') }}"></div>
            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">David Teixeira Ferraz</h3>
                <p><strong>Undergraduate Student</strong></p>
                <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/david-teixeira-ferraz/">LabBCES/david-teixeira-ferraz</a></p>
            </div>
        </div>
    <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-4 hidden-xs"><img alt="arthur picture" class="img-rounded" style="width: 80%; height: auto;margin-top: 20px" src="{{ url_for('static', filename='img/contact/arthur_shuzo_red_200.png') }}"></div>
        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12"><h3 class="banner-green">Arthur Shuzo Owtake Cardoso</h3>
            <p><strong>Undergraduate Student</strong></p>
            <p><i class="fa fa-globe text-muted"></i> <a href="https://labbces.netlify.app/author/arthur-shuzo-owtake-cardoso/">LabBCES/arthur-shuzo-owtake-cardoso</a></p>
        </div>
    </div>
</div>
{% endblock %}

CoNekT/conekt/templates/static_pages/data_resources.html
{% extends 'base.html' %}

{% block title %}
    CoNekT Grasses - Data Resources
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li><a href="{{ url_for('main.screen') }}">Home</a></li>
        <li class="active"><strong>Data Resources</strong></li>
    </ol>
       
    <h1 class="banner-green">Data Resources</h1>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://phytozome-next.jgi.doe.gov/" target="_blank"><img alt="phytozone picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;"  src="{{ url_for('static', filename='img/data_resources/phytozone_250x250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://www.ncbi.nlm.nih.gov/" target="_blank"><img alt="ncbi picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/data_resources/ncbi_logo_250x250.png') }}"></a>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs"><a href="https://figshare.com/projects/Sugarcane_Pan-transcriptome/130586" target="_blank"><img alt="figshare picture" class="rounded" style="width: 100%; height: auto; margin-top: 20px;" src="{{ url_for('static', filename='img/data_resources/figshare_250x250.png') }}"></a>
        </div> 
    </div>  
    
</div>

    
{% endblock %}

CoNekT/conekt/templates/static_pages/disclaimer.html
{% extends 'base.html' %}

{% block title %}
    CoNekT Grasses - Disclaimer
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li><a href="{{ url_for('main.screen') }}">Home</a></li>
        <li class="active"><strong>Disclaimer</strong></li>
    </ol>
    <h1>Disclaimer</h1>

    <p><a href="{{ url_for('main.screen') }}">CoNekT Grasses</a> derives from <a href="https://conekt.sbs.ntu.edu.sg/">CoNekT</a>.
        All source code used as basis to develop CoNekT Grasses was obtained from the <a href="https://github.com/sepro/CoNekT">CoNekT GitHub repository</a>,
        which is available under the <a href="https://github.com/sepro/CoNekT/blob/master/LICENSE.md">MIT license</a>.</p>

    <p>All CoNekT Grasses source code, including new features, will be publicly available
        upon publication on the <a href="https://github.com/labbces/conekt_grasses">CoNekT Grasses GitHub</a>
        under the <a href="https://github.com/labbces">Laboratory of Computational, Evolutionary and Systems Biology (LabBCES) organization</a>.</p>

    <p>By using this site, you agree to the <a href="{{ url_for('main.privacy_policy') }}" class="text-muted">Privacy policy</a>.</p>
</p>
</div>

</div>
{% endblock %}

CoNekT/conekt/templates/static_pages/features.html
{% extends 'base.html' %}

{% block title %}
    CoNekT - Features
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li><a href="{{ url_for('main.screen') }}">Home</a></li>
        <li class="active"><strong>Features</strong></li>
    </ol>
    <h1>CoNekT Features</h1>

    <h3 class="banner-green" >Search</h3>

    <p>CoNekT comes packed with functions to quickly find relevant data. A general keyword search is available on
    each page (search box top right corner), though for more complex searches users have the tools below at their
    disposal.</p>

    <div class="row equal">
        {% if g.blast_enabled %}
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6" >
            <div class="panel panel-default panel-card">
            <div class="panel-heading">BLAST</div>
                <a href="{{ url_for('blast.blast_main') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/blast.png') }}"/>
                </a>
            <div class="panel-body">
                <p>Find <strong>sequences</strong> in CoNekT similar to a query sequence</p>
            </div>
        </div>
        </div>
        {% endif %}
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6" >
            <div class="panel panel-default panel-card">
            <div class="panel-heading">Enriched clusters</div>
                <a href="{{ url_for('search.search_enriched_clusters') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/enrichment.png') }}"/>
                </a>
            <div class="panel-body">
                <p>Find <strong>clusters</strong> enriched for a selected GO-term</p>
            </div>
        </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6" >
            <div class="panel panel-default panel-card">
            <div class="panel-heading">Specific profiles</div>
                <a href="{{ url_for('search.search_specific_profiles') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/specific_profile.png') }}" />
                </a>
            <div class="panel-body">
                <p>Find <strong>sequences</strong> which are expressed specifically in certain conditions or tissues</p>
            </div>
        </div>
        </div>

    </div>

    <h3 class="banner-green" >Tools</h3>

    <p>Tools allow users to either compare data included in CoNekT or create plots using a custom set of genes.</p>
    <div class="row equal">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 panel-card" >
            <div class="panel panel-default">
                <div class="panel-heading">Compare profiles</div>
                <a href="{{ url_for('profile_comparison.profile_comparison_main') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/profile_comparison.png') }}" />
                </a>
                <div class="panel-body">
                    <p>Allows users to <strong>compare the expression profiles</strong> from a custom set of genes in a graph</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 panel-card" >
            <div class="panel panel-default">
                <div class="panel-heading">Conserved specificity</div>
                <a href="{{ url_for('specificity_comparison.specificity_comparison_main') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/specificity.png') }}" />
                </a>
                <div class="panel-body">
                    <p><strong>Compare genes specifically expressed</strong> in a certain conditions in two species</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 panel-card" >
            <div class="panel panel-default">
                <div class="panel-heading">Custom network</div>
                <a href="{{ url_for('custom_network.custom_network_main') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/network.png') }}" />
                </a>
                <div class="panel-body">
                    <p><strong>Show co-expression network</strong> only taking a custom set of genes into account</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 panel-card" >
            <div class="panel panel-default">
                <div class="panel-heading">Heatmap</div>
                <a href="{{ url_for('heatmap.heatmap_main') }}">
                    <img class="img-responsive img-card" src="{{ url_for('static', filename='img/cards/heatmap.png') }}" />
                </a>
                <div class="panel-body">
                    <p>Allows users to <strong>compare the expression profiles</strong> from a custom set of genes in a heatmap</p>
                </div>
            </div>
        </div>
    </div>

</div>

</div>
{% endblock %}

CoNekT/conekt/templates/static_pages/main.html
{% extends 'base.html' %}

{% block title %}
    CoNekT Grasses : Co-expression Network Toolkit for Grasses
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li class="active">Home</li>
    </ol>

    <div class="row">
        <div class="col-lg-12">

            <div style="overflow:hidden">
                <div>
                    <img width="150" height="150" src="{{ url_for('static', filename='img/conekt_grasses_logo.png') }}" style="float:left;margin-right:25px;margin-top:5px;margin-bottom:20px;" />
                    <h1><b>CoNekT Grasses</b> is a platform derived from <b><a href="https://conekt.sbs.ntu.edu.sg/">CoNekT</a></b> dedicated to the visualization and analysis of co-expression and co-function networks of grasses.</h1>
                    {% if g.msg %}
                    <div><span class="global-message"><strong>{{ g.msg_title|safe }}: </strong>{{ g.msg|safe }}</span></div>
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="col-lg-12">
            <div id="new-alert" class="alert alert-info alert-dismissible" role="alert" style="display: none">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>New ?</strong> Check out our CoNekT's features <a href="{{ url_for('main.features') }}">here</a> ! </div>
            <div class="panel panel-default" style="background-color: #DFF0D8">
                <div class="panel-body">
                    <form  role="search" method="post" id="search-form-main" name="search-form-main" action="{{ url_for('search.simple') }}">
                        {{ g.search_form.csrf_token }}
                        <div>
                            <div class="from-group input-group">
                                {{ g.search_form.terms(class_="form-control", placeholder="Search") }}
                                <div class="input-group-btn"><button type="submit" class="btn btn-primary" value="Search" data-toggle="modal" data-target="#loaderModal">Search</button></div>
                            </div>
                            {% if keyword_examples %}
                            <span>e.g.
                                {% for ke in keyword_examples %}
                                <a href="{{ url_for('search.search_single_keyword', keyword=ke) }}">{{ ke }}</a>,
                                {% endfor %}
                                ...</span>
                            {% endif %}

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
          <div id="featureCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#featureCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#featureCarousel" data-slide-to="1"></li>
              <li data-target="#featureCarousel" data-slide-to="2"></li>
              <li data-target="#featureCarousel" data-slide-to="3"></li>
              <li data-target="#featureCarousel" data-slide-to="4"></li>
              <li data-target="#featureCarousel" data-slide-to="5"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <div class="carousel-div">
                    <div class="row">
                        <div class="col-xs-2"><div style="margin-top:30px"><span style="color:#fff;font-size:36px;background-color:#0b8b0b;border-radius:4px;padding:10px"><i class="fa fa-search" ></i></span></div></div>
                        <div class="col-xs-10">
                            <h3>Quickly retrieve genes</h3>
                            <p>Use our <a href="{{ url_for('search.advanced') }}">Search</a> function {% if g.blast_enabled -%}or <a href="{{ url_for('blast.blast_main') }}">BLAST</a>{%- endif %} to quickly find genes of interest.</p>
                        </div>
                    </div>
                </div>
              </div>

              <div class="item">
                <div class="carousel-div">
                    <h3>Expression profiles and expression specificity</h3>
                    <p>See in which tissues and conditions a gene of interest is expressed or find genes <a href="{{ url_for('search.search_specific_profiles') }}">specifically expressed</a> in a certain tissue/condition.</p>
                </div>
              </div>

              <div class="item">
                <div class="carousel-div">
                    <h3>Co-expression networks</h3>
                    <p>Browse co-expression networks based on thousands of publicly available RNA-Seq samples! <a href="{{ url_for('search.search_enriched_clusters') }}">Find clusters</a> of co-expressed genes enriched for certain functions.</p>
                </div>
              </div>

              <div class="item">
                <div class="carousel-div">
                    <h3>Co-expression clusters</h3>
                    <p>Browse co-expression networks based on thousands of publicly available RNA-Seq samples! <a href="{{ url_for('search.search_enriched_clusters') }}">Find cluster</a> of co-expressed genes enriched for certain functions.</p>
                </div>
              </div>

              <div class="item">
                <div class="carousel-div">
                    <h3>Analyse custom gene sets</h3>
                    <p>Create <a href="{{ url_for('heatmap.heatmap_main') }}">heatmap</a> and <a href="{{ url_for('profile_comparison.profile_comparison_main') }}">expression profiles</a> for user defined sets of genes. Build a <a href="{{ url_for('custom_network.custom_network_main') }}">custom co-expression network</a> for a set of selected genes.</p>
                </div>
              </div>

              <div class="item">
                <div class="carousel-div">
                    <div class="col-xs-2"><div style="margin-top:30px"><span style="color:#fff;font-size:36px;background-color:#0b8b0b;border-radius:4px;padding:10px"><i class="fa fa-github"></i></span></div></div>
                    <div class="col-xs-10">
                        <h3>CoNekT Grasses is open-source</h3>
                        <p>Head to <a href="https://github.com/labbces/conekt_grasses">GitHub</a> for a copy of the source if you want to host your own version with in-house data or other species!</p>
                    </div>
                </div>
              </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#featureCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#featureCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        </div>
    </div>
    <!-- <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="panel panel-success"  style="height:300px; overflow-y:scroll">
              <div class="panel-heading">News</div>
              <div class="panel-body">
                  {% for n in news %}
                  <div>
                      <p>{{ n.message_markup }}</p>
                      <p class="text-muted text-right">by {{ n.posted_by }} (<strong>{{n.posted_formatted}}</strong>)</p>
                      {% if not loop.last %}
                        <hr />
                      {% endif %}
                  </div>
                  {% else %}
                      <p><em>No news messages found</em></p>
                  {% endfor %}
              </div>
            </div>
        </div>
        {% if g.twitter_handle %}
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="panel panel-default" style="height:300px; overflow-y:scroll">
                <a class="twitter-timeline" href="https://twitter.com/{{g.twitter_handle}}">Tweets by {{g.twitter_handle}}</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </div>
        {% endif %}
    </div> -->
</div>

</div>
{% endblock %}

{% block extrajs %}
<script src="{{ url_for('static', filename='js/js.cookie.js') }}"></script>
<script>
    $(document).ready(function() {
        // check cookie
        var visited = Cookies.get('visited');

        if (visited == null) {
            $('#new-alert').show();
        }

        // set cookie
        Cookies.set('visited', 'yes', { expires: 1000 });
    });
</script>
{% endblock %}

CoNekT/conekt/templates/static_pages/privacy_policy.html
{% extends 'base.html' %}

{% block title %}
    CoNekT Grasses - Privacy policy
{% endblock %}

{% block container %}
<div class="top-pad">
    <ol class="breadcrumb">
        <li><a href="{{ url_for('main.screen') }}">Home</a></li>
        <li class="active"><strong>Disclaimer</strong></li>
    </ol>
    <h1>CoNekT Grasses Privacy policy</h1>

    <p>No personal data needs to be entered to use CoNekT Grasses. Data submitted through the CoNekT Grasses BLAST interface is
    stored anonymously for the duration of the analysis. Results can be accessed using the personalized URL provided
    upon submitting the sequence for up to one week.</p>

    {% if g.privacy %}
    <p>If in any case personal date should be (unintentionally) collected, stored or used, these <a href="{{ g.privacy }}">privacy policies</a> apply.</p>
    {% endif %}

</p>
</div>

</div>
{% endblock %}